# Authentication Secrets Examples
# Registry and Git authentication configurations
#
# ============================================================================
# ⚠️  SECURITY WARNING - READ BEFORE USING
# ============================================================================
#
# This file contains TEMPLATE EXAMPLES ONLY with placeholder values.
#
# DO NOT:
#   - Commit real credentials, tokens, or passwords to Git
#   - Replace placeholders in this file and push to version control
#   - Store actual secrets in any Git repository
#
# FOR PRODUCTION USE:
#   - Apply secrets directly to your cluster (never commit them)
#   - Use sealed-secrets, external-secrets-operator, or Azure Key Vault CSI
#   - Store credentials in a secrets manager (1Password, Vault, Azure Key Vault)
#   - Use workload identity where possible (Azure Workload Identity, IRSA)
#
# Placeholder values in this file:
#   - <base64(username:password)>  - Replace with actual base64-encoded creds
#   - <SSH_PRIVATE_KEY_CONTENT>    - Replace with actual SSH private key
#   - ghp_xxxxxxxxxxxxxxxxxxxx     - Replace with actual GitHub PAT
#   - <your-azure-devops-PAT>      - Replace with actual Azure DevOps PAT
#
# ============================================================================
---
# Docker Hub Registry Secret
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-creds
  namespace: argocd
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "<base64(username:password)>"
        }
      }
    }
---
# GitHub Container Registry (GHCR) Secret
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-creds
  namespace: argocd
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "<base64(username:PAT)>"
        }
      }
    }
---
# Azure Container Registry (ACR) Secret
apiVersion: v1
kind: Secret
metadata:
  name: acr-creds
  namespace: argocd
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "myregistry.azurecr.io": {
          "auth": "<base64(SP_APP_ID:SP_PASSWORD)>"
        }
      }
    }
---
# Git SSH Key Secret
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-key
  namespace: argocd
type: Opaque
stringData:
  sshPrivateKey: |
    <SSH_PRIVATE_KEY_CONTENT>
    # Generate with: ssh-keygen -t ed25519 -C "argocd-image-updater"
---
# Git HTTPS Token Secret (GitHub PAT)
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
type: Opaque
stringData:
  username: git
  password: ghp_xxxxxxxxxxxxxxxxxxxx
---
# Azure DevOps PAT Secret
apiVersion: v1
kind: Secret
metadata:
  name: azure-devops-creds
  namespace: argocd
type: Opaque
stringData:
  username: ""  # Leave empty for PAT
  password: <your-azure-devops-PAT>
---
# Registries ConfigMap Example
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  log.level: info
  registries.conf: |
    registries:
      - name: Docker Hub
        prefix: docker.io
        api_url: https://registry-1.docker.io
        credentials: pullsecret:argocd/dockerhub-creds
        default: true
      - name: GitHub Container Registry
        prefix: ghcr.io
        api_url: https://ghcr.io
        credentials: pullsecret:argocd/ghcr-creds
      - name: Azure Container Registry
        prefix: myregistry.azurecr.io
        api_url: https://myregistry.azurecr.io
        credentials: pullsecret:argocd/acr-creds
---
# Credential Reference Formats:
# pullsecret:<namespace>/<secret-name>     - Docker config secret
# secret:<namespace>/<secret-name>#<key>   - Specific key from secret
# env:<VARIABLE_NAME>                      - Environment variable
# ext:/path/to/script                      - External script (stdout = password)
#
# Generate base64 auth value:
# echo -n 'username:password' | base64
